### ISSUE TITLE
Kivy graph crashing

### ISSUE THREAD

**Issue by Asi4nn** [Leo-Wang-Toronto/Python-Graphing-Calculator-v2#1]
Zooming in and out causes this error and I have no idea why:

 Traceback (most recent call last):
   File "D:\Documents\Programming\Kivy\Python-Graphing-Calculator-v2\main.py", line 110, in <module>
     GraphingCalculatorApp().run()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\app.py", line 855, in run
     runTouchApp()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 504, in runTouchApp
     EventLoop.window.mainloop()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 747, in mainloop
     self._mainloop()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\core\window\window_sdl2.py", line 479, in _mainloop
     EventLoop.idle()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\base.py", line 339, in idle
     Clock.tick()
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy\clock.py", line 591, in tick
     self._process_events()
   File "kivy\_clock.pyx", line 384, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 414, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 412, in kivy._clock.CyClockBase._process_events
   File "kivy\_clock.pyx", line 167, in kivy._clock.ClockEvent.tick
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy_garden\graph\__init__.py", line 560, in _redraw_all
     xpoints_major, xpoints_minor = self._redraw_x(*args)
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy_garden\graph\__init__.py", line 592, in _redraw_x
     self.xmax)
   File "C:\Users\leowa\AppData\Local\Programs\Python\Python37\lib\site-packages\kivy_garden\graph\__init__.py", line 312, in _get_ticks
     points_minor[k2] = m * tick_dist + s_min
 IndexError: list assignment index out of range

**Comment by Asi4nn** [comment]
Seems to be caused by the minor tick property of Graph, I'm going to leave out minor ticks for now.
